export enum Role {
  PATIENT = 'PATIENT',
  PROVIDER = 'PROVIDER',
  ADMIN = 'ADMIN'
}

export enum ProviderSpecialty {
  GENERAL = 'GENERAL',
  RADIOLOGY = 'RADIOLOGY',
  CARDIOLOGY = 'CARDIOLOGY',
  NEUROLOGY = 'NEUROLOGY',
  ORTHOPEDICS = 'ORTHOPEDICS',
  OTHER = 'OTHER'
}

export enum NotificationType {
  NEW_SHARE = 'NEW_SHARE',
  NEW_MESSAGE = 'NEW_MESSAGE',
  ANNOTATION_ADDED = 'ANNOTATION_ADDED',
  SECURITY_ALERT = 'SECURITY_ALERT',
  SYSTEM_UPDATE = 'SYSTEM_UPDATE',
  UPLOAD_COMPLETE = 'UPLOAD_COMPLETE',
  FILE_SHARED = 'FILE_SHARED',
  FILE_DOWNLOADED = 'FILE_DOWNLOADED',
  FILE_DELETED = 'FILE_DELETED',
  PROCESSING_ERROR = 'PROCESSING_ERROR',
  APPOINTMENT_CREATED = 'APPOINTMENT_CREATED',
  APPOINTMENT_COMPLETED = 'APPOINTMENT_COMPLETED',
  APPOINTMENT_CANCELLED = 'APPOINTMENT_CANCELLED',
  APPOINTMENT_NO_SHOW = 'APPOINTMENT_NO_SHOW'
}

export enum ImageType {
  XRAY = 'XRAY',
  MRI = 'MRI',
  CT = 'CT',
  ULTRASOUND = 'ULTRASOUND',
  OTHER = 'OTHER'
}

export enum ImageStatus {
  PROCESSING = 'PROCESSING',
  READY = 'READY',
  ERROR = 'ERROR'
}

export enum AppointmentStatus {
  SCHEDULED = 'SCHEDULED',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  NO_SHOW = 'NO_SHOW'
}

export enum ShareType {
  LINK = 'LINK',
  DIRECT = 'DIRECT',
  EMAIL = 'EMAIL'
}

export enum SharePermission {
  VIEW = 'VIEW',
  COMMENT = 'COMMENT',
  EDIT = 'EDIT'
}

export enum AnnotationType {
  MARKER = 'MARKER',
  MEASUREMENT = 'MEASUREMENT',
  TEXT = 'TEXT',
  DRAWING = 'DRAWING'
}

export enum PatientStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  PENDING = 'PENDING'
}

export enum HealthMetricType {
  BLOOD_PRESSURE = 'BLOOD_PRESSURE',
  HEART_RATE = 'HEART_RATE',
  TEMPERATURE = 'TEMPERATURE',
  WEIGHT = 'WEIGHT',
  HEIGHT = 'HEIGHT',
  BLOOD_SUGAR = 'BLOOD_SUGAR',
  OXYGEN_SATURATION = 'OXYGEN_SATURATION',
  PAIN_LEVEL = 'PAIN_LEVEL'
} 